### ISSUE TITLE
Create initial product screen

### ISSUE THREAD

**Issue by faermanj** [CaravanaCloud/ecomarkets#10]

**Comment by faermanj** [comment]
Before working on this ticket, please check our bounties eligibility at https://github.com/CaravanaCloud/.github/blob/main/BOUNTIES.md

/bounty 20.00

**Comment by RutamBhagat** [comment]
@faermanj can you please provide a bit more details about the issue

**Comment by Anshul1811** [comment]
Can I take this one @faermanj ? 
And kindly provide more details.
