### ISSUE TITLE
Design initial shopping basket

### ISSUE THREAD

**Issue by faermanj** [CaravanaCloud/ecomarkets#11]

**Comment by faermanj** [comment]
Before working on this ticket, please check our bounties eligibility at https://github.com/CaravanaCloud/.github/blob/main/BOUNTIES.md

/bounty 20.00

**Comment by Amanullah1002** [comment]
Hello , I can see that cart page is already there , do I need to Refactor it or need to make something else . Please provide me more information so I can head in the correct direction.
![image](https://github.com/CaravanaCloud/ecomarkets/assets/73701731/bad3790c-0d29-4b46-9ddb-5b7cb849ba64)

**Comment by atulkrs** [comment]
@faermanj can u please clarify some more about this.
