### ISSUE TITLE
Populate initial test database

### ISSUE THREAD

**Issue by faermanj** [CaravanaCloud/ecomarkets#12]
Create a simple test database for development

**Comment by faermanj** [comment]
Before working on this ticket, please check our bounties eligibility at https://github.com/CaravanaCloud/.github/blob/main/BOUNTIES.md

/bounty 20.00

**Comment by ibishal** [comment]
@faermanj can i start working on it?

**Comment by Amanullah1002** [comment]
Please provide more information on this issue.
